### ISSUE TITLE
安装rep.txt出现报错。

### ISSUE THREAD

**Issue by kay6666** [ice-doom/EyeJo#4]
Traceback (most recent call last):
      File "/tmp/pip-install-vde1inbu/pycurl/setup.py", line 223, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/local/python3/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/local/python3/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vde1inbu/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-vde1inbu/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-vde1inbu/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/tmp/pip-install-vde1inbu/pycurl/setup.py", line 227, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vde1inbu/pycurl/
You are using pip version 19.0.3, however version 21.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ice-doom** [comment]
少安装了libcurl4-openssl-dev这个包，不行的话就安装`apt-get install libssl-dev libcurl4-openssl-dev python-dev curl`。最好使用使用docker部署项目

**Comment by kay6666** [comment]
已经解决了。是curl版本太低，感谢帮助
