### ISSUE TITLE
子域名只用了11秒，随后未进行下一步信息搜集以及漏洞扫描

### ISSUE THREAD

**Issue by kesonn** [ice-doom/EyeJo#9]
![image](https://user-images.githubusercontent.com/36539433/119122173-d3532380-ba60-11eb-965c-b66256141b01.png)

**Comment by kesonn** [comment]
![image](https://user-images.githubusercontent.com/36539433/119122402-0f868400-ba61-11eb-8f8d-592e789a800a.png)
端口都是空的

**Comment by ice-doom** [comment]
这里结束时间表示执行到当前状态的时间，状态表示当前执行的任务状态。像图中表示当前正在执行子域名收集还未完成，结束时间表示执行到子域名收集的上一个任务的结束时间。是正常的

**Comment by kesonn** [comment]
请问哪里可以看到具体日志进度？

**Comment by ice-doom** [comment]
可以进去容器查看下日志，`docker exec -it eyejo_worker tail -50 celery.log`

**Comment by kesonn** [comment]
![image](https://user-images.githubusercontent.com/36539433/119262137-bf4c2500-bc0c-11eb-969e-d81a354e775c.png)

**Comment by kesonn** [comment]
看到官方还没修复这个bug？
https://github.com/shmilylty/OneForAll/issues/201

**Comment by kesonn** [comment]
![image](https://user-images.githubusercontent.com/36539433/119263035-05ef4e80-bc10-11eb-969e-70250ccea8f8.png)

**Comment by ice-doom** [comment]
这个等修复后，就更新一下。另一个bug，是由于进行域名解析不出IP的目标导致获取的时候为None，需要调整代码。

**Comment by ice-doom** [comment]
目前已知的bug已解决

**Comment by kesonn** [comment]
![image](https://user-images.githubusercontent.com/36539433/119748702-0f0a4500-bec8-11eb-9cef-b189d781dbf3.png)
4天过去了，还是在子域名搜集，重新搭建一个可以修复这个问题吗

**Comment by ice-doom** [comment]
可以尝试重新拉取镜像和git，再启动环境添加目标。本地测试过，这种状况是可以正常执行完成。
你子域名收集的数量有多少，1个域名基本上几分钟能收集完成。如果超过半天/一天卡住在同一个状态下可以查看日志是在是否正常运行。

**Comment by kesonn** [comment]
![image](https://user-images.githubusercontent.com/36539433/119914974-1008a880-bf94-11eb-83cf-d38cf2a2f3e1.png)
发现一天过去了，还是在同一个状态

**Comment by ice-doom** [comment]
提供下日志记录、输入的子域名收集数量

**Comment by kesonn** [comment]
___             _ _ 
 ___ ___ ___|  _|___ ___ ___| | | {v0.4.3 #dev}
| . |   | -_|  _| . |  _| .'| | | 
|___|_|_|___|_| |___|_| |__,|_|_| git.io/fjHT1

OneForAll is under development, please update before each use!
[2021-05-27 12:48:27,408: WARNING/ForkPoolWorker-2] [*] Starting OneForAll @ 2021-05-27 12:48:27
[2021-05-27 12:48:29,942: WARNING/ForkPoolWorker-2] Exception in thread
[2021-05-27 12:48:29,942: WARNING/ForkPoolWorker-2] netcraft
[2021-05-27 12:48:29,942: WARNING/ForkPoolWorker-2] :
[2021-05-27 12:48:29,942: WARNING/ForkPoolWorker-2] Traceback (most recent call last):
[2021-05-27 12:48:29,942: WARNING/ForkPoolWorker-2] File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2021-05-27 12:48:29,944: WARNING/ForkPoolWorker-2] self.run()
[2021-05-27 12:48:29,944: WARNING/ForkPoolWorker-2] File "/usr/lib/python3.8/threading.py", line 870, in run
[2021-05-27 12:48:29,944: WARNING/ForkPoolWorker-2] self._target(*self._args, **self._kwargs)
[2021-05-27 12:48:29,944: WARNING/ForkPoolWorker-2] File "/root/eyejo/plugin/OneForAll/modules/datasets/netcraft.py", line 80, in run
[2021-05-27 12:48:29,944: WARNING/ForkPoolWorker-2] query.run()
[2021-05-27 12:48:29,944: WARNING/ForkPoolWorker-2] File "/root/eyejo/plugin/OneForAll/modules/datasets/netcraft.py", line 66, in run
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] self.query()
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] File "/root/eyejo/plugin/OneForAll/modules/datasets/netcraft.py", line 39, in query
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] if not self.bypass_verification():
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] File "/root/eyejo/plugin/OneForAll/modules/datasets/netcraft.py", line 29, in bypass_verification
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] cookie_value = self.cookie['netcraft_js_verification_challenge']
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.8/dist-packages/requests/cookies.py", line 328, in __getitem__
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] return self._find_no_duplicates(name)
[2021-05-27 12:48:29,945: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.8/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
[2021-05-27 12:48:29,946: WARNING/ForkPoolWorker-2] raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
[2021-05-27 12:48:29,946: WARNING/ForkPoolWorker-2] KeyError
[2021-05-27 12:48:29,946: WARNING/ForkPoolWorker-2] :
[2021-05-27 12:48:29,946: WARNING/ForkPoolWorker-2] "name='netcraft_js_verification_challenge', domain=None, path=None"
[2021-05-27 13:02:05,728: ERROR/ForkPoolWorker-2] Task EyeJoTask[f07efda4-aef6-4a88-bcc6-3a191a475a70] raised unexpected: KeyError('ip')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/eyejo/EyeJo/tasks.py", line 389, in task_func
    alltask.run()
  File "/root/eyejo/EyeJo/tasks.py", line 371, in run
    self.run_subdomain_collect()
  File "/root/eyejo/EyeJo/tasks.py", line 72, in run_subdomain_collect
    subdomain_collect.main(self.target_dict.get('domain'), self.project_id, self.asset_id, self.task_id, self.yaml_config)
  File "/root/eyejo/plugin/subdomain_collect.py", line 62, in main
    TargetHandle.GetIpInfo(schema_target_dict, project_id, asset_id, yaml_config, task_id).main()
  File "/root/eyejo/projectApp/utils/TargetHandle.py", line 112, in main
    target_ip_set.update({get_target(self.c_schema_target_dict['ip'].pop(x)).get('new_target') for x in range(len(self.c_schema_target_dict['ip']) - 1, -1, -1) if not check_private_ip(get_target(self.c_schema_target_dict['ip'][x]).get('new_target'))})
KeyError: 'ip'

**Comment by kesonn** [comment]
一个主域名：站点数量：0

域名数量：7180

IP数量：7172

**Comment by ice-doom** [comment]
麻烦将日志文件拷贝出来，发送到我邮箱里吧，protp6@protonmail.com

**Comment by kesonn** [comment]
大佬，我发过去啦，麻烦看看

**Comment by ice-doom** [comment]
没有收到，垃圾箱也没有

**Comment by kesonn** [comment]
麻烦再看看？

**Comment by ice-doom** [comment]
好，已收到

**Comment by ice-doom** [comment]
重新拉取镜像，运行试试看，以修改这处。

**Comment by kesonn** [comment]
[2021-05-30 21:24:20,099: WARNING/ForkPoolWorker-2] cookie_value = self.cookie['netcraft_js_verification_challenge']
[2021-05-30 21:24:20,100: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.8/dist-packages/requests/cookies.py", line 328, in __getitem__
[2021-05-30 21:24:20,100: WARNING/ForkPoolWorker-2] return self._find_no_duplicates(name)
[2021-05-30 21:24:20,100: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.8/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
[2021-05-30 21:24:20,100: WARNING/ForkPoolWorker-2] raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
[2021-05-30 21:24:20,100: WARNING/ForkPoolWorker-2] KeyError
[2021-05-30 21:24:20,100: WARNING/ForkPoolWorker-2] :
[2021-05-30 21:24:20,100: WARNING/ForkPoolWorker-2] "name='netcraft_js_verification_challenge', domain=None, path=None"
[2021-05-30 21:36:39,573: ERROR/ForkPoolWorker-2] Task EyeJoTask[8e2156d1-2e19-4d3c-87e8-c564414fb19b] raised unexpected: KeyError('ip')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/eyejo/EyeJo/tasks.py", line 389, in task_func
    alltask.run()
  File "/root/eyejo/EyeJo/tasks.py", line 371, in run
    self.run_subdomain_collect()
  File "/root/eyejo/EyeJo/tasks.py", line 72, in run_subdomain_collect
    subdomain_collect.main(self.target_dict.get('domain'), self.project_id, self.asset_id, self.task_id, self.yaml_config)
  File "/root/eyejo/plugin/subdomain_collect.py", line 62, in main
    TargetHandle.GetIpInfo(schema_target_dict, project_id, asset_id, yaml_config, task_id).main()
  File "/root/eyejo/projectApp/utils/TargetHandle.py", line 112, in main
    target_ip_set.update({get_target(self.c_schema_target_dict['ip'].pop(x)).get('new_target') for x in range(len(self.c_schema_target_dict['ip']) - 1, -1, -1) if not check_private_ip(get_target(self.c_schema_target_dict['ip'][x]).get('new_target'))})
KeyError: 'ip'
一个小时过去了，还是一样抱错额，在子域名搜集

**Comment by ice-doom** [comment]
把目标域名发我测试下，发我邮箱

**Comment by kesonn** [comment]
已解决该问题，感谢
